export const items = [
    { id: 1, title: "The Great Gatsby", content: "A novel set in the Jazz Age that explores themes of wealth and society.", date: "1925-04-10" },
    { id: 2, title: "To Kill a Mockingbird", content: "A story of racial injustice in the Deep South.", date: "1960-07-11" },
    { id: 3, title: "1984", content: "A dystopian novel depicting a totalitarian society under constant surveillance.", date: "1949-06-08" },
    { id: 4, title: "Pride and Prejudice", content: "A romantic novel that explores issues of class and marriage.", date: "1813-01-28" },
    { id: 5, title: "Moby-Dick", content: "A tale of obsession and revenge between a captain and a giant whale.", date: "1851-10-18" },
    { id: 6, title: "War and Peace", content: "An epic novel set during the Napoleonic Wars.", date: "1869-01-01" },
    { id: 7, title: "Crime and Punishment", content: "A psychological novel about a man who commits a crime and faces moral dilemmas.", date: "1866-01-01" },
    { id: 8, title: "The Odyssey", content: "An ancient Greek epic about Odysseus’s journey home after the Trojan War.", date: "800 BC" },
    { id: 9, title: "Jane Eyre", content: "A gothic romance novel about a young orphan who finds love and independence.", date: "1847-10-16" },
    { id: 10, title: "The Catcher in the Rye", content: "A coming-of-age novel about a teenager’s journey of self-discovery.", date: "1951-07-16" },
    { id: 11, title: "Brave New World", content: "A dystopian story of a society conditioned by genetic engineering and social conformity.", date: "1932-08-01" },
    { id: 12, title: "The Brothers Karamazov", content: "A novel about family, faith, and moral conflicts.", date: "1880-01-01" },
    { id: 13, title: "Anna Karenina", content: "A tragedy that explores love, family, and social expectations.", date: "1877-01-01" },
    { id: 14, title: "Wuthering Heights", content: "A gothic novel about passion and revenge on the moors.", date: "1847-12-01" },
    { id: 15, title: "Frankenstein", content: "A science fiction novel about the consequences of playing God.", date: "1818-01-01" },
    { id: 16, title: "The Hobbit", content: "A fantasy adventure of a hobbit's journey to reclaim treasure.", date: "1937-09-21" },
    { id: 17, title: "The Divine Comedy", content: "An epic poem detailing a journey through Hell, Purgatory, and Paradise.", date: "1320-01-01" },
    { id: 18, title: "Fahrenheit 451", content: "A dystopian novel about a future where books are banned and burned.", date: "1953-10-19" },
    { id: 19, title: "Don Quixote", content: "A satirical novel about a man’s adventures as a self-styled knight.", date: "1605-01-16" },
    { id: 20, title: "Les Misérables", content: "A story of redemption, justice, and compassion in revolutionary France.", date: "1862-01-01" },
    { id: 21, title: "The Iliad", content: "An ancient Greek epic poem recounting the Trojan War.", date: "800 BC" },
    { id: 22, title: "The Count of Monte Cristo", content: "A tale of betrayal, vengeance, and redemption.", date: "1844-08-28" },
    { id: 23, title: "Great Expectations", content: "A coming-of-age story that examines class and ambition.", date: "1861-01-01" },
    { id: 24, title: "The Scarlet Letter", content: "A story of sin, guilt, and redemption in Puritan New England.", date: "1850-03-16" },
    { id: 25, title: "Dracula", content: "A gothic horror novel about a vampire’s pursuit of conquest and survival.", date: "1897-05-26" },
    { id: 26, title: "One Hundred Years of Solitude", content: "A magical realism novel about the Buendía family's generational saga.", date: "1967-05-30" },
  { id: 27, title: "The Sun Also Rises", content: "A novel about a group of expatriates traveling from Paris to Spain.", date: "1926-10-22" },
  { id: 28, title: "Catch-22", content: "A satirical novel on the absurdity of war and bureaucracy.", date: "1961-11-10" },
  { id: 29, title: "The Grapes of Wrath", content: "A story of a family's struggle during the Great Depression.", date: "1939-04-14" },
  { id: 30, title: "Beloved", content: "A novel about the haunting legacy of slavery.", date: "1987-09-18" },
  { id: 31, title: "The Stranger", content: "A philosophical novel that explores existentialism and absurdity.", date: "1942-04-01" },
  { id: 32, title: "A Tale of Two Cities", content: "A historical novel set during the French Revolution.", date: "1859-04-30" },
  { id: 33, title: "Ulysses", content: "A modernist novel that parallels the Odyssey in a single day in Dublin.", date: "1922-02-02" },
  { id: 34, title: "Madame Bovary", content: "A novel about a woman's pursuit of romance and escape from her dull life.", date: "1857-01-01" },
  { id: 35, title: "Slaughterhouse-Five", content: "A satirical anti-war novel about time travel and trauma.", date: "1969-03-31" },
  { id: 36, title: "Invisible Man", content: "A novel exploring racial discrimination and identity.", date: "1952-04-14" },
  { id: 37, title: "The Old Man and the Sea", content: "A novella about a fisherman’s struggle with a giant marlin.", date: "1952-09-01" },
  { id: 38, title: "Lolita", content: "A controversial novel about obsession and manipulation.", date: "1955-09-15" },
  { id: 39, title: "The Bell Jar", content: "A semi-autobiographical novel on mental health and society.", date: "1963-01-14" },
  { id: 40, title: "Dune", content: "A science fiction novel about politics, religion, and power.", date: "1965-08-01" },
  { id: 41, title: "Heart of Darkness", content: "A novella about a journey into the Congo and colonialism.", date: "1899-01-01" },
  { id: 42, title: "The Road", content: "A post-apocalyptic novel about survival and father-son bonds.", date: "2006-09-26" },
  { id: 43, title: "Rebecca", content: "A gothic novel about jealousy and secrets.", date: "1938-08-01" },
  { id: 44, title: "Gone with the Wind", content: "A romance novel set during the American Civil War.", date: "1936-06-30" },
  { id: 45, title: "The Handmaid's Tale", content: "A dystopian novel about a society with strict gender roles.", date: "1985-09-01" },
  { id: 46, title: "The Alchemist", content: "A novel about a young man’s journey to realize his dreams.", date: "1988-04-01" },
  { id: 47, title: "The Picture of Dorian Gray", content: "A novel about vanity and the pursuit of eternal youth.", date: "1890-07-20" },
  { id: 48, title: "Alice's Adventures in Wonderland", content: "A fantasy novel about a girl who falls down a rabbit hole.", date: "1865-11-26" },
  { id: 49, title: "Mrs. Dalloway", content: "A modernist novel set in a single day in London.", date: "1925-05-14" },
  { id: 50, title: "The Call of the Wild", content: "An adventure novel about a dog’s survival in the Yukon.", date: "1903-01-01" },
  { id: 51, title: "The Sound and the Fury", content: "A novel about the decline of a Southern family.", date: "1929-10-07" },
  { id: 52, title: "Middlemarch", content: "A novel about life in a provincial town in 19th-century England.", date: "1871-12-01" },
  { id: 53, title: "A Clockwork Orange", content: "A dystopian novel exploring free will and morality.", date: "1962-01-01" },
  { id: 54, title: "The Jungle", content: "A novel highlighting the plight of workers in the meatpacking industry.", date: "1906-02-26" },
  { id: 55, title: "Paradise Lost", content: "An epic poem about the fall of man and Satan's rebellion.", date: "1667-01-01" },
  { id: 56, title: "Gulliver's Travels", content: "A satire on human nature and society through fantastical voyages.", date: "1726-01-01" },
  { id: 57, title: "The Aeneid", content: "An epic poem about the founding of Rome.", date: "19 BC" },
  { id: 58, title: "The Hunchback of Notre-Dame", content: "A historical novel set around the Notre-Dame Cathedral.", date: "1831-01-01" },
  { id: 59, title: "The Adventures of Huckleberry Finn", content: "A novel about a boy's adventures on the Mississippi River.", date: "1884-12-10" },
  { id: 60, title: "The Trial", content: "A novel about a man who faces an unjust court system.", date: "1925-04-01" },
  { id: 61, title: "Dr. Jekyll and Mr. Hyde", content: "A novella about the dual nature of humanity.", date: "1886-01-05" },
  { id: 62, title: "On the Road", content: "A novel about the countercultural road trips of the Beat Generation.", date: "1957-09-05" },
  { id: 63, title: "Sense and Sensibility", content: "A novel exploring love and societal expectations.", date: "1811-10-30" },
  { id: 64, title: "The Canterbury Tales", content: "A collection of stories told by pilgrims traveling to Canterbury.", date: "1400-01-01" },
  { id: 65, title: "Leaves of Grass", content: "A poetry collection celebrating democracy and individualism.", date: "1855-07-04" },
  { id: 66, title: "Of Mice and Men", content: "A novella about friendship and dreams during the Great Depression.", date: "1937-01-01" },
  { id: 67, title: "The Time Machine", content: "A science fiction novel about time travel and society.", date: "1895-01-01" },
  { id: 68, title: "David Copperfield", content: "A novel about the life and growth of a young man.", date: "1850-01-01" },
  { id: 69, title: "Vanity Fair", content: "A satire on British society in the 19th century.", date: "1847-01-01" },
  { id: 70, title: "The Metamorphosis", content: "A novella about a man who transforms into an insect.", date: "1915-01-01" },
  { id: 71, title: "The Three Musketeers", content: "An adventure novel about friendship and heroism.", date: "1844-01-01" },
  { id: 72, title: "The Glass Menagerie", content: "A play about family dynamics and dreams deferred.", date: "1944-12-26" },
  { id: 73, title: "A Farewell to Arms", content: "A novel about love and loss during World War I.", date: "1929-09-27" },
  { id: 74, title: "The Importance of Being Earnest", content: "A satirical play about identity and marriage.", date: "1895-02-14" },
  { id: 75, title: "The Red Badge of Courage", content: "A novel about fear and courage during the Civil War.", date: "1895-01-01" },
  { id: 76, title: "The Portrait of a Lady", content: "A novel about a young woman's struggle with independence.", date: "1881-01-01" },
  { id: 77, title: "The Prince", content: "A treatise on political power and strategy.", date: "1532-01-01" },
  { id: 78, title: "Bleak House", content: "A novel exposing the injustices of the British legal system.", date: "1853-01-01" },
  { id: 79, title: "The Call of the Wild", content: "An adventure novel set in the Yukon during the gold rush.", date: "1903-01-01" },
  { id: 80, title: "Candide", content: "A satire on optimism and the human condition.", date: "1759-01-01" },
  { id: 81, title: "The Last of the Mohicans", content: "A historical novel set during the French and Indian War.", date: "1826-01-01" },
  { id: 82, title: "Walden", content: "A reflection on simple living in natural surroundings.", date: "1854-08-09" },
  { id: 83, title: "Little Women", content: "A novel about the lives of four sisters growing up in New England.", date: "1868-09-30" },
  { id: 84, title: "Native Son", content: "A novel exploring racial tensions and social issues.", date: "1940-01-01" },
  { id: 85, title: "To the Lighthouse", content: "A novel about family, art, and the passage of time.", date: "1927-05-05" },
  { id: 86, title: "The Master and Margarita", content: "A novel blending satire and fantasy in Soviet Russia.", date: "1967-01-01" },
  { id: 87, title: "Robinson Crusoe", content: "A novel about survival and self-discovery on a deserted island.", date: "1719-04-25" },
  { id: 88, title: "Don Juan", content: "A satirical poem about a libertine's adventures.", date: "1819-01-01" },
  { id: 89, title: "The Magic Mountain", content: "A novel about life, death, and philosophy in a sanatorium.", date: "1924-01-01" },
  { id: 90, title: "The Death of Ivan Ilyich", content: "A novella about the existential reflections of a dying man.", date: "1886-01-01" },
  { id: 91, title: "Things Fall Apart", content: "A novel about African society and colonialism.", date: "1958-01-01" },
  { id: 92, title: "The Charterhouse of Parma", content: "A novel of love and ambition in post-Napoleonic Europe.", date: "1839-01-01" },
  { id: 93, title: "Eugene Onegin", content: "A novel in verse exploring love and friendship in Russian society.", date: "1833-01-01" },
  { id: 94, title: "Sons and Lovers", content: "A novel about family, love, and social expectations.", date: "1913-01-01" },
  { id: 95, title: "The Way of All Flesh", content: "A novel criticizing Victorian society and family dynamics.", date: "1903-01-01" },
  { id: 96, title: "The Good Soldier", content: "A novel about love and deception in Edwardian England.", date: "1915-03-17" },
  { id: 97, title: "The Tenant of Wildfell Hall", content: "A novel about a woman escaping an abusive marriage.", date: "1848-06-01" },
  { id: 98, title: "Far from the Madding Crowd", content: "A novel about love and rural life in England.", date: "1874-01-01" },
  { id: 99, title: "White Fang", content: "A novel about a wolf-dog's journey to domestication.", date: "1906-01-01" },
  { id: 100, title: "The Sorrows of Young Werther", content: "A novel about unrequited love and emotional turmoil.", date: "1774-01-01" }
];
  