export const items = [
    { id: 1, title: "The Great Gatsby", content: "A novel set in the Jazz Age that explores themes of wealth and society.", date: "1925-04-10" },
    { id: 2, title: "To Kill a Mockingbird", content: "A story of racial injustice in the Deep South.", date: "1960-07-11" },
    { id: 3, title: "1984", content: "A dystopian novel depicting a totalitarian society under constant surveillance.", date: "1949-06-08" },
    { id: 4, title: "Pride and Prejudice", content: "A romantic novel that explores issues of class and marriage.", date: "1813-01-28" },
    { id: 5, title: "Moby-Dick", content: "A tale of obsession and revenge between a captain and a giant whale.", date: "1851-10-18" },
    { id: 6, title: "War and Peace", content: "An epic novel set during the Napoleonic Wars.", date: "1869-01-01" },
    { id: 7, title: "Crime and Punishment", content: "A psychological novel about a man who commits a crime and faces moral dilemmas.", date: "1866-01-01" },
    { id: 8, title: "The Odyssey", content: "An ancient Greek epic about Odysseus’s journey home after the Trojan War.", date: "800 BC" },
    { id: 9, title: "Jane Eyre", content: "A gothic romance novel about a young orphan who finds love and independence.", date: "1847-10-16" },
    { id: 10, title: "The Catcher in the Rye", content: "A coming-of-age novel about a teenager’s journey of self-discovery.", date: "1951-07-16" },
    { id: 11, title: "Brave New World", content: "A dystopian story of a society conditioned by genetic engineering and social conformity.", date: "1932-08-01" },
    { id: 12, title: "The Brothers Karamazov", content: "A novel about family, faith, and moral conflicts.", date: "1880-01-01" },
    { id: 13, title: "Anna Karenina", content: "A tragedy that explores love, family, and social expectations.", date: "1877-01-01" },
    { id: 14, title: "Wuthering Heights", content: "A gothic novel about passion and revenge on the moors.", date: "1847-12-01" },
    { id: 15, title: "Frankenstein", content: "A science fiction novel about the consequences of playing God.", date: "1818-01-01" },
    { id: 16, title: "The Hobbit", content: "A fantasy adventure of a hobbit's journey to reclaim treasure.", date: "1937-09-21" },
    { id: 17, title: "The Divine Comedy", content: "An epic poem detailing a journey through Hell, Purgatory, and Paradise.", date: "1320-01-01" },
    { id: 18, title: "Fahrenheit 451", content: "A dystopian novel about a future where books are banned and burned.", date: "1953-10-19" },
    { id: 19, title: "Don Quixote", content: "A satirical novel about a man’s adventures as a self-styled knight.", date: "1605-01-16" },
    { id: 20, title: "Les Misérables", content: "A story of redemption, justice, and compassion in revolutionary France.", date: "1862-01-01" },
    { id: 21, title: "The Iliad", content: "An ancient Greek epic poem recounting the Trojan War.", date: "800 BC" },
    { id: 22, title: "The Count of Monte Cristo", content: "A tale of betrayal, vengeance, and redemption.", date: "1844-08-28" },
    { id: 23, title: "Great Expectations", content: "A coming-of-age story that examines class and ambition.", date: "1861-01-01" },
    { id: 24, title: "The Scarlet Letter", content: "A story of sin, guilt, and redemption in Puritan New England.", date: "1850-03-16" },
    { id: 25, title: "Dracula", content: "A gothic horror novel about a vampire’s pursuit of conquest and survival.", date: "1897-05-26" },
    { id: 26, title: "One Hundred Years of Solitude", content: "A magical realism novel about the Buendía family's generational saga.", date: "1967-05-30" },
  { id: 27, title: "The Sun Also Rises", content: "A novel about a group of expatriates traveling from Paris to Spain.", date: "1926-10-22" },
  { id: 28, title: "Catch-22", content: "A satirical novel on the absurdity of war and bureaucracy.", date: "1961-11-10" },
  { id: 29, title: "The Grapes of Wrath", content: "A story of a family's struggle during the Great Depression.", date: "1939-04-14" },
  { id: 30, title: "Beloved", content: "A novel about the haunting legacy of slavery.", date: "1987-09-18" },
  { id: 31, title: "The Stranger", content: "A philosophical novel that explores existentialism and absurdity.", date: "1942-04-01" },
  { id: 32, title: "A Tale of Two Cities", content: "A historical novel set during the French Revolution.", date: "1859-04-30" },
  { id: 33, title: "Ulysses", content: "A modernist novel that parallels the Odyssey in a single day in Dublin.", date: "1922-02-02" },
  { id: 34, title: "Madame Bovary", content: "A novel about a woman's pursuit of romance and escape from her dull life.", date: "1857-01-01" },
  { id: 35, title: "Slaughterhouse-Five", content: "A satirical anti-war novel about time travel and trauma.", date: "1969-03-31" },
  { id: 36, title: "Invisible Man", content: "A novel exploring racial discrimination and identity.", date: "1952-04-14" },
  { id: 37, title: "The Old Man and the Sea", content: "A novella about a fisherman’s struggle with a giant marlin.", date: "1952-09-01" },
  { id: 38, title: "Lolita", content: "A controversial novel about obsession and manipulation.", date: "1955-09-15" },
  { id: 39, title: "The Bell Jar", content: "A semi-autobiographical novel on mental health and society.", date: "1963-01-14" },
  { id: 40, title: "Dune", content: "A science fiction novel about politics, religion, and power.", date: "1965-08-01" },
  { id: 41, title: "Heart of Darkness", content: "A novella about a journey into the Congo and colonialism.", date: "1899-01-01" },
  { id: 42, title: "The Road", content: "A post-apocalyptic novel about survival and father-son bonds.", date: "2006-09-26" },
  { id: 43, title: "Rebecca", content: "A gothic novel about jealousy and secrets.", date: "1938-08-01" },
  { id: 44, title: "Gone with the Wind", content: "A romance novel set during the American Civil War.", date: "1936-06-30" },
  { id: 45, title: "The Handmaid's Tale", content: "A dystopian novel about a society with strict gender roles.", date: "1985-09-01" },
  { id: 46, title: "The Alchemist", content: "A novel about a young man’s journey to realize his dreams.", date: "1988-04-01" },
  { id: 47, title: "The Picture of Dorian Gray", content: "A novel about vanity and the pursuit of eternal youth.", date: "1890-07-20" },
  { id: 48, title: "Alice's Adventures in Wonderland", content: "A fantasy novel about a girl who falls down a rabbit hole.", date: "1865-11-26" },
  { id: 49, title: "Mrs. Dalloway", content: "A modernist novel set in a single day in London.", date: "1925-05-14" },
  { id: 50, title: "The Call of the Wild", content: "An adventure novel about a dog’s survival in the Yukon.", date: "1903-01-01" }
];
  